#!/bin/bash

export JASPERLIB=/usr/lib64
export JASPERINC=/usr/include

module purge
module load pbs
module load dot
module load intel-fc/15.0.3.187
module load intel-cc/15.0.3.187
module load openmpi/1.8.8
module load netcdf/4.3.3.1

./configure

echo Submitting compilation to queue.
qsub -N UPPcompile <<EOF
#PBS -l walltime=0:30:00
#PBS -l mem=1GB
#PBS -l ncpus=1
#PBS -j oe
#PBS -q express
#PBS -l wd
#PBS -l software=intel-compiler

module purge
module load pbs
module load dot
module load intel-fc/15.0.3.187
module load intel-cc/15.0.3.187
module load openmpi/1.8.8
module load netcdf/4.3.3.1


./compile

EOF

